### ISSUE TITLE
save urls

### ISSUE THREAD

**Issue by adnjoo** [adnjoo/fast-youtube-summary#45]
as a user if logged in i want to see my urls that i submitted for summary

## Feature: View Submitted URLs for Summary (History Page)

**As a user, if logged in, I want to see my URLs that I submitted for summary.**

### Goals
- Display a history of URLs submitted by the logged-in user for summary.
- Ensure only the logged-in user can see their own submitted URLs.

### Tasks
- [x] **Supabase Database**
  - [x] Create a `History` table with fields:
    - `id` (Primary Key)
    - `user_id` (Foreign Key, references `auth.users.id`)
    - `url` (Text)
    - `created_at` (Timestamp, defaults to `now()`)
  - [x] Set up row-level security (RLS) policies to ensure users can only access their own history records.
    - Policy Example:
      ```sql
      CREATE POLICY "Users can view their own history"
      ON public.history
      FOR SELECT
      USING (auth.uid() = user_id);
      ```
- [ ] **Frontend**
  - [x] Design the `/history` page using ShadCN components.
  - [x] Fetch the history data from Supabase and display a list of URLs with submission dates.
  - [ ] Implement pagination if there are many URLs.
- [x] **Authentication**
  - [x] Ensure users are authenticated before accessing the `/history` page.
  - [x] Redirect unauthenticated users to the login page if they try to access `/history`.
- [ ] **Testing**
  - [ ] Write tests for the Supabase `History` table to ensure RLS policies are correctly enforced.
  - [ ] Write frontend tests to confirm that only logged-in users can access their history.
### Notes
- **Data Caching**: Consider caching the data to improve page load times if history grows large.
- **Optional**: Allow users to delete or edit their history entries.
### Dependencies
- Supabase table migration to create the `History` table.
- RLS policy setup in Supabase.
### Estimated Time
- **Backend (Supabase setup and API)**: 2 hours
- **Frontend**: 4 hours
